server:
  port: 8086
  error:
    include-message: always

spring:
  h2:
    console:
      enabled: true
      path: /h2-ui
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  driverClassName: org.h2.Driver

  jpa:

    database-platform: com.example.stock.management.AxonPostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: false

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operationsSorter: method
    path: /api/swagger.html